version: "1"

stack_defaults:


stacks:
    # The key of is the immutable slug of your stack
    # which you will find in the URL.
   debugtest: &shared
 before_init:
        - terraform import aws_instance.my_instance i-1234567890abcdef0
